name: Continuous Deployment

on:
  push:
    branches:
      - CD

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build
    - name: Test
      run: npm test
    - name: Deploy to Production
      run: <Votre commande de déploiement>
      if: github.ref == 'refs/heads/master' and success()
